import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  Pressable,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { MaterialIcons } from '@expo/vector-icons';
import { Colors, Typography, Spacing, BorderRadius, Shadows } from '../../constants/theme';
import HODHeader from '../../components/HODHeader';
import HODBottomNav from '../../components/HODBottomNav';
import PrimaryButton from '../../components/PrimaryButton';
import {
  getAcademicContext,
  getTimetableVersion,
  getClassTimetable,
  subscribeTimetableVersion,
  TIMETABLE_STATUSES,
} from '../../constants/demoData';

export default function ClassTimetableReviewScreen() {
  const router = useRouter();
  const context = getAcademicContext();
  const activeSection = context.section || 'CSE-C';
  const [timetableVersion, setTimetableVersion] = useState(getTimetableVersion());
  const [selectedDay, setSelectedDay] = useState('all');

  useEffect(() => {
    const unsub = subscribeTimetableVersion((v) => setTimetableVersion({ ...v }));
    return unsub;
  }, []);

  const rawSessions = getClassTimetable({ section: activeSection, department: 'CSE' });

  // If runtime sessions have not yet been generated by the solver, provide the draft matrix structure for review
  const fallbackDraftSessions = [
    { id: 'S1', day: 'MON', period: 'P1', time: '09:15-10:05', code: '22CSC14', name: 'Compiler Design', faculty: 'Ms. C. Navamani', room: 'LH-302', type: 'THEORY' },
    { id: 'S2', day: 'MON', period: 'P2', time: '10:05-10:55', code: '22CSC15', name: 'Cloud Computing', faculty: 'Dr. M. Kavitha', room: 'LH-302', type: 'THEORY' },
    { id: 'S3', day: 'MON', period: 'P3', time: '11:10-12:00', code: '22CSE03', name: 'Cryptography', faculty: 'Dr. T. Rajesh', room: 'LH-302', type: 'ELECTIVE' },
    { id: 'S4', day: 'MON', period: 'P4', time: '12:00-12:50', code: '22CSO01', name: 'Open Elective I', faculty: 'Inter-Dept Guide', room: 'LH-101', type: 'OTHER' },
    { id: 'S5', day: 'MON', period: 'P5', time: '01:45-02:35', code: '22CSC14', name: 'Compiler Design', faculty: 'Ms. C. Navamani', room: 'LH-302', type: 'THEORY' },
    { id: 'S6', day: 'MON', period: 'P6', time: '02:35-03:25', code: '22CSC15', name: 'Cloud Computing', faculty: 'Dr. M. Kavitha', room: 'LH-302', type: 'THEORY' },
    { id: 'S7', day: 'MON', period: 'P7', time: '03:40-04:30', code: 'LIB01', name: 'Library & Mentoring', faculty: 'Ms. C. Navamani', room: 'Central Lib', type: 'OTHER' },
    { id: 'S8', day: 'TUE', period: 'P1-P4', time: '09:15-12:50', code: '22CSL07', name: 'Compiler Design Laboratory (4P Continuous)', faculty: 'Ms. C. Navamani & Mrs. S. Deepa', room: 'Lab 3 (Systems)', type: 'LAB', isSpan: true },
    { id: 'S9', day: 'TUE', period: 'P5', time: '01:45-02:35', code: '22CSE03', name: 'Cryptography', faculty: 'Dr. T. Rajesh', room: 'LH-302', type: 'ELECTIVE' },
    { id: 'S10', day: 'TUE', period: 'P6', time: '02:35-03:25', code: '22CSC14', name: 'Compiler Design', faculty: 'Ms. C. Navamani', room: 'LH-302', type: 'THEORY' },
    { id: 'S11', day: 'TUE', period: 'P7', time: '03:40-04:30', code: 'SOCIETY', name: 'CSI Student Branch Activity', faculty: 'Dr. K. Senthil Kumar', room: 'Seminar Hall', type: 'OTHER' },
    { id: 'S12', day: 'WED', period: 'P1', time: '09:15-10:05', code: '22CSC15', name: 'Cloud Computing', faculty: 'Dr. M. Kavitha', room: 'LH-302', type: 'THEORY' },
    { id: 'S13', day: 'WED', period: 'P2', time: '10:05-10:55', code: '22CSC14', name: 'Compiler Design', faculty: 'Ms. C. Navamani', room: 'LH-302', type: 'THEORY' },
    { id: 'S14', day: 'WED', period: 'P3', time: '11:10-12:00', code: '22CSE03', name: 'Cryptography', faculty: 'Dr. T. Rajesh', room: 'LH-302', type: 'ELECTIVE' },
    { id: 'S15', day: 'WED', period: 'P4', time: '12:00-12:50', code: '22CSO01', name: 'Open Elective I', faculty: 'Inter-Dept Guide', room: 'LH-101', type: 'OTHER' },
    { id: 'S16', day: 'WED', period: 'P5-P7', time: '01:45-04:30', code: 'SPORTS', name: 'Physical Education / Proctorship', faculty: 'Ms. C. Navamani', room: 'Ground / Hall', type: 'OTHER' },
    { id: 'S17', day: 'THU', period: 'P1-P4', time: '09:15-12:50', code: '22CSL08', name: 'Cloud & Network Systems Lab (4P Continuous)', faculty: 'Dr. M. Kavitha & Mr. P. Vignesh', room: 'Server Lab 2', type: 'LAB', isSpan: true },
    { id: 'S18', day: 'THU', period: 'P5', time: '01:45-02:35', code: '22CSC15', name: 'Cloud Computing', faculty: 'Dr. M. Kavitha', room: 'LH-302', type: 'THEORY' },
    { id: 'S19', day: 'THU', period: 'P6', time: '02:35-03:25', code: '22CSC14', name: 'Compiler Design', faculty: 'Ms. C. Navamani', room: 'LH-302', type: 'THEORY' },
    { id: 'S20', day: 'THU', period: 'P7', time: '03:40-04:30', code: 'COUNSEL', name: 'Class Advisor Interaction Hour', faculty: 'Ms. C. Navamani', room: 'LH-302', type: 'OTHER' },
    { id: 'S21', day: 'FRI', period: 'P1', time: '09:15-10:05', code: '22CSC14', name: 'Compiler Design', faculty: 'Ms. C. Navamani', room: 'LH-302', type: 'THEORY' },
    { id: 'S22', day: 'FRI', period: 'P2', time: '10:05-10:55', code: '22CSC15', name: 'Cloud Computing', faculty: 'Dr. M. Kavitha', room: 'LH-302', type: 'THEORY' },
    { id: 'S23', day: 'FRI', period: 'P3', time: '11:10-12:00', code: '22CSE03', name: 'Cryptography', faculty: 'Dr. T. Rajesh', room: 'LH-302', type: 'ELECTIVE' },
    { id: 'S24', day: 'FRI', period: 'P4', time: '12:00-12:50', code: '22CSO01', name: 'Open Elective I', faculty: 'Inter-Dept Guide', room: 'LH-101', type: 'OTHER' },
    { id: 'S25', day: 'FRI', period: 'P5-P7', time: '01:45-04:30', code: 'PBL01', name: 'Project-Based Learning / Seminar', faculty: 'Ms. C. Navamani & Dr. M. Kavitha', room: 'Project Lab', type: 'LAB', isSpan: true },
  ];

  const sessions = rawSessions.length > 0 ? rawSessions : fallbackDraftSessions;

  const days = [
    { id: 'all', label: 'All Days' },
    { id: 'MON', label: 'Mon (7P)' },
    { id: 'TUE', label: 'Tue (Lab)' },
    { id: 'WED', label: 'Wed (7P)' },
    { id: 'THU', label: 'Thu (Lab)' },
    { id: 'FRI', label: 'Fri (7P)' },
  ];

  const filteredSessions =
    selectedDay === 'all'
      ? sessions
      : sessions.filter((s) => s.day === selectedDay);

  const displayStatus = timetableVersion.status === 'NO_TIMETABLE' ? 'PENDING HOD REVIEW' : timetableVersion.status;
  const isApproved = displayStatus === 'APPROVED' || displayStatus === 'PUBLISHED';

  return (
    <SafeAreaView style={styles.safeContainer} edges={['top']}>
      <HODHeader
        title="Class Timetable Review"
        showBack={true}
        activeCohort={`${context.year || 'III'} / ${context.semester || 'V'} / ${activeSection}`}
      />

      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
      >
        {/* Review Context Header Card */}
        <View style={styles.contextCard}>
          <View style={styles.contextHeaderRow}>
            <View style={styles.reviewTag}>
              <MaterialIcons name="rate-review" size={13} color="#FFFFFF" />
              <Text style={styles.reviewTagText}>HOD TIMETABLE AUDIT DESK</Text>
            </View>
            <View
              style={[
                styles.statusBadge,
                isApproved ? styles.statusApproved : styles.statusPending,
              ]}
            >
              <Text
                style={[
                  styles.statusBadgeText,
                  isApproved ? styles.statusApprovedText : styles.statusPendingText,
                ]}
              >
                {displayStatus}
              </Text>
            </View>
          </View>

          <Text style={styles.gridTitle}>
            CSE • {context.year || 'III Year'} • {context.semester || 'Sem V'} • {activeSection}
          </Text>
          <Text style={styles.gridMeta}>
            Version: Draft v4.2 • Prepared by AC Mr. R. Manikandan • 35 Scheduled Periods
          </Text>

          {/* Quick Metrics */}
          <View style={styles.metricsBar}>
            <View style={styles.metricItem}>
              <Text style={styles.metricVal}>35/35</Text>
              <Text style={styles.metricLabel}>Periods Filled</Text>
            </View>
            <View style={styles.metricDivider} />
            <View style={styles.metricItem}>
              <Text style={styles.metricVal}>0</Text>
              <Text style={styles.metricLabel}>Hard Conflicts</Text>
            </View>
            <View style={styles.metricDivider} />
            <View style={styles.metricItem}>
              <Text style={styles.metricVal}>2 Labs</Text>
              <Text style={styles.metricLabel}>4P Spans OK</Text>
            </View>
          </View>
        </View>

        {/* Day Filter Tabs */}
        <ScrollView
          horizontal
          showsHorizontalScrollIndicator={false}
          contentContainerStyle={styles.tabsRow}
        >
          {days.map((d) => {
            const isSelected = selectedDay === d.id;
            return (
              <Pressable
                key={d.id}
                style={[styles.dayTab, isSelected && styles.dayTabActive]}
                onPress={() => setSelectedDay(d.id)}
              >
                <Text style={[styles.dayTabText, isSelected && styles.dayTabTextActive]}>
                  {d.label}
                </Text>
              </Pressable>
            );
          })}
        </ScrollView>

        {/* Timetable Session Grid */}
        <View style={styles.sessionList}>
          {filteredSessions.map((session) => (
            <View key={session.id} style={styles.sessionCard}>
              <View style={styles.sessionTopRow}>
                <View style={styles.periodBadge}>
                  <Text style={styles.periodText}>{session.period}</Text>
                  <Text style={styles.dayText}>{session.day}</Text>
                </View>

                <View style={styles.courseInfoCol}>
                  <View style={styles.codeRow}>
                    <Text style={styles.courseCodeText}>{session.code}</Text>
                    <View
                      style={[
                        styles.catBadge,
                        session.type === 'THEORY'
                          ? styles.catTheory
                          : session.type === 'LAB'
                          ? styles.catLab
                          : styles.catElective,
                      ]}
                    >
                      <Text style={styles.catBadgeText}>{session.type}</Text>
                    </View>
                  </View>
                  <Text style={styles.courseNameText}>{session.name}</Text>
                </View>

                <View style={styles.roomBox}>
                  <MaterialIcons name="room" size={12} color="#64748B" />
                  <Text style={styles.roomText}>{session.room}</Text>
                </View>
              </View>

              <View style={styles.sessionBottomRow}>
                <MaterialIcons name="person" size={14} color="#0F2942" />
                <Text style={styles.facultyText}>{session.faculty}</Text>
                <Text style={styles.timeTag}>{session.time}</Text>
              </View>
            </View>
          ))}
        </View>

        {/* Primary Action Button */}
        <View style={styles.ctaBox}>
          <Text style={styles.ctaTitle}>Ready to Ratify Timetable?</Text>
          <Text style={styles.ctaDesc}>
            Review constraint clearance and issue statutory approval order or request revision from the Academic Coordinator.
          </Text>
          <PrimaryButton
            title="Proceed to HOD Timetable Approval"
            icon="gavel"
            iconRight="arrow-forward"
            onPress={() => router.push('/hod/approval')}
            style={styles.ctaBtn}
          />
        </View>
      </ScrollView>

      <HODBottomNav activeTab="timetable" />
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeContainer: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: Spacing.margin,
    paddingTop: Spacing.md,
    paddingBottom: Spacing.xl,
  },
  contextCard: {
    backgroundColor: '#0F2942',
    borderRadius: BorderRadius.lg,
    padding: Spacing.md,
    marginBottom: Spacing.md,
    ...Shadows.sm,
  },
  contextHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  reviewTag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2563EB',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
    gap: 4,
  },
  reviewTagText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
  },
  statusApproved: {
    backgroundColor: '#ECFDF5',
  },
  statusApprovedText: {
    color: '#059669',
    fontSize: 9,
    fontWeight: '800',
  },
  statusPending: {
    backgroundColor: '#FEF3C7',
  },
  statusPendingText: {
    color: '#D97706',
    fontSize: 9,
    fontWeight: '800',
  },
  gridTitle: {
    ...Typography.titleMedium,
    color: '#FFFFFF',
    fontWeight: '900',
    fontSize: 17,
    marginBottom: 2,
  },
  gridMeta: {
    ...Typography.bodySmall,
    color: '#CBD5E1',
    fontSize: 11,
    marginBottom: 10,
  },
  metricsBar: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: BorderRadius.md,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  metricItem: {
    alignItems: 'center',
  },
  metricVal: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  metricLabel: {
    color: '#94A3B8',
    fontSize: 10,
    marginTop: 2,
  },
  metricDivider: {
    width: 1,
    height: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
  },
  tabsRow: {
    gap: 8,
    paddingBottom: Spacing.md,
  },
  dayTab: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: BorderRadius.full,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: Colors.outlineVariant,
  },
  dayTabActive: {
    backgroundColor: '#0F2942',
    borderColor: '#0F2942',
  },
  dayTabText: {
    fontSize: 11,
    fontWeight: '700',
    color: Colors.onSurfaceVariant,
  },
  dayTabTextActive: {
    color: '#FFFFFF',
  },
  sessionList: {
    gap: 10,
    marginBottom: Spacing.lg,
  },
  sessionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: BorderRadius.md,
    padding: 12,
    borderWidth: 1,
    borderColor: Colors.outlineVariant,
    ...Shadows.sm,
  },
  sessionTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    marginBottom: 8,
  },
  periodBadge: {
    backgroundColor: '#F1F5F9',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    alignItems: 'center',
    minWidth: 42,
  },
  periodText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#0F2942',
  },
  dayText: {
    fontSize: 9,
    fontWeight: '700',
    color: '#64748B',
  },
  courseInfoCol: {
    flex: 1,
  },
  codeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 2,
  },
  courseCodeText: {
    fontSize: 13,
    fontWeight: '900',
    color: '#0F2942',
  },
  catBadge: {
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 3,
  },
  catBadgeText: {
    fontSize: 8,
    fontWeight: '800',
  },
  catTheory: {
    backgroundColor: '#EFF6FF',
    color: '#2563EB',
  },
  catLab: {
    backgroundColor: '#FEF3C7',
    color: '#D97706',
  },
  catElective: {
    backgroundColor: '#ECFDF5',
    color: '#059669',
  },
  courseNameText: {
    fontSize: 12,
    fontWeight: '700',
    color: Colors.primary,
  },
  roomBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 4,
  },
  roomText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#64748B',
  },
  sessionBottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    paddingTop: 6,
    gap: 6,
  },
  facultyText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#0F2942',
    flex: 1,
  },
  timeTag: {
    fontSize: 10,
    color: '#64748B',
    fontWeight: '600',
  },
  ctaBox: {
    backgroundColor: '#FFFFFF',
    borderRadius: BorderRadius.lg,
    padding: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.outlineVariant,
    ...Shadows.sm,
  },
  ctaTitle: {
    ...Typography.titleSmall,
    color: '#0F2942',
    fontWeight: '800',
    fontSize: 14,
    marginBottom: 2,
  },
  ctaDesc: {
    ...Typography.bodySmall,
    color: Colors.onSurfaceVariant,
    fontSize: 11,
    marginBottom: 12,
  },
  ctaBtn: {
    backgroundColor: '#0F2942',
  },
});
