const TimetableVersion = require('../models/TimetableVersion');
const TimetableSession = require('../models/TimetableSession');
const AcademicContext = require('../models/AcademicContext');
const Faculty = require('../models/Faculty');

async function seedTimetable() {
  console.log('[Seed] Seeding published timetable version and faculty session grid...');

  // Locate academic context for III Year CSE Section A
  let context = await AcademicContext.findOne({
    department: 'CSE',
    year: 'III Year',
    section: 'A',
  });

  if (!context) {
    context = await AcademicContext.create({
      academicYear: '2026-27',
      semester: 'Odd Semester',
      department: 'CSE',
      year: 'III Year',
      section: 'A',
      program: 'UG',
      status: 'ACTIVE',
    });
  }

  // Clear existing seeded timetable sessions and versions
  await TimetableSession.deleteMany({});
  await TimetableVersion.deleteMany({});

  const version = await TimetableVersion.create({
    academicYear: '2026-27',
    semester: 'Odd Semester',
    department: 'CSE',
    year: 'III Year',
    section: 'A',
    version: 1,
    versionLabel: 'v1.0 (Official Semester Rollout)',
    status: 'PUBLISHED',
    generatedBy: 'Mr. R. Manikandan (AC)',
    submittedBy: 'Mr. R. Manikandan (AC)',
    approvedBy: 'Dr. T. Rajasekaran (HOD)',
    approvedAt: new Date(),
    publishedAt: new Date(),
    hardConflicts: 0,
    totalScheduledPeriods: 35,
  });

  const sessions = [
    // --- MONDAY ---
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC14',
      courseName: 'Compiler Design',
      facultyId: 'FWL-03',
      facultyName: 'Dr. S. Karpusamy',
      day: 'MON',
      period: 'P1',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC10',
      courseName: 'Operating Systems',
      facultyId: 'FWL-22',
      facultyName: 'Mr. R. Manikandan',
      day: 'MON',
      period: 'P2',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC01',
      courseName: 'Advanced Data Structures',
      facultyId: 'FWL-01',
      facultyName: 'Dr. T. Rajasekaran',
      day: 'MON',
      period: 'P3',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC14',
      courseName: 'Compiler Design',
      facultyId: 'FWL-03',
      facultyName: 'Dr. S. Karpusamy',
      day: 'MON',
      period: 'P4',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC15',
      courseName: 'Computer Networks',
      facultyId: 'FWL-04',
      facultyName: 'Dr. A. Balamurugan',
      day: 'MON',
      period: 'P5',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC12',
      courseName: 'Software Engineering',
      facultyId: 'FWL-05',
      facultyName: 'Mrs. P. Shanthi',
      day: 'MON',
      period: 'P6',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSS01',
      courseName: 'Library & Online Certification',
      facultyId: 'FWL-05',
      facultyName: 'Mrs. P. Shanthi',
      day: 'MON',
      period: 'P7',
      room: 'Digital Library',
      sessionType: 'OTHER',
      duration: 1,
    },

    // --- TUESDAY ---
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC15',
      courseName: 'Computer Networks',
      facultyId: 'FWL-04',
      facultyName: 'Dr. A. Balamurugan',
      day: 'TUE',
      period: 'P1',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC12',
      courseName: 'Software Engineering',
      facultyId: 'FWL-05',
      facultyName: 'Mrs. P. Shanthi',
      day: 'TUE',
      period: 'P2',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC10',
      courseName: 'Operating Systems',
      facultyId: 'FWL-22',
      facultyName: 'Mr. R. Manikandan',
      day: 'TUE',
      period: 'P3',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSM01',
      courseName: 'Mentor Proctoring & Interaction',
      facultyId: 'FWL-03',
      facultyName: 'Dr. S. Karpusamy',
      day: 'TUE',
      period: 'P4',
      room: 'LH-101',
      sessionType: 'SAS',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSL05',
      courseName: 'Compiler Design Laboratory',
      facultyId: 'FWL-03',
      facultyName: 'Dr. S. Karpusamy',
      day: 'TUE',
      period: 'P5',
      room: 'Systems Lab 2',
      sessionType: 'LAB',
      duration: 3,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSL05',
      courseName: 'Compiler Design Laboratory',
      facultyId: 'FWL-03',
      facultyName: 'Dr. S. Karpusamy',
      day: 'TUE',
      period: 'P6',
      room: 'Systems Lab 2',
      sessionType: 'LAB',
      duration: 3,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSL05',
      courseName: 'Compiler Design Laboratory',
      facultyId: 'FWL-03',
      facultyName: 'Dr. S. Karpusamy',
      day: 'TUE',
      period: 'P7',
      room: 'Systems Lab 2',
      sessionType: 'LAB',
      duration: 3,
    },

    // --- WEDNESDAY ---
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC01',
      courseName: 'Advanced Data Structures',
      facultyId: 'FWL-01',
      facultyName: 'Dr. T. Rajasekaran',
      day: 'WED',
      period: 'P1',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC14',
      courseName: 'Compiler Design',
      facultyId: 'FWL-03',
      facultyName: 'Dr. S. Karpusamy',
      day: 'WED',
      period: 'P2',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSL02',
      courseName: 'Operating Systems Laboratory',
      facultyId: 'FWL-22',
      facultyName: 'Mr. R. Manikandan',
      day: 'WED',
      period: 'P3',
      room: 'Systems Lab 1',
      sessionType: 'LAB',
      duration: 2,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSL02',
      courseName: 'Operating Systems Laboratory',
      facultyId: 'FWL-22',
      facultyName: 'Mr. R. Manikandan',
      day: 'WED',
      period: 'P4',
      room: 'Systems Lab 1',
      sessionType: 'LAB',
      duration: 2,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC12',
      courseName: 'Software Engineering',
      facultyId: 'FWL-05',
      facultyName: 'Mrs. P. Shanthi',
      day: 'WED',
      period: 'P5',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC15',
      courseName: 'Computer Networks',
      facultyId: 'FWL-04',
      facultyName: 'Dr. A. Balamurugan',
      day: 'WED',
      period: 'P6',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CST01',
      courseName: 'Technical Seminar & Communication',
      facultyId: 'FWL-04',
      facultyName: 'Dr. A. Balamurugan',
      day: 'WED',
      period: 'P7',
      room: 'Seminar Hall 2',
      sessionType: 'TUTORIAL',
      duration: 1,
    },

    // --- THURSDAY ---
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSL06',
      courseName: 'Networks Laboratory',
      facultyId: 'FWL-04',
      facultyName: 'Dr. A. Balamurugan',
      day: 'THU',
      period: 'P1',
      room: 'Network Lab',
      sessionType: 'LAB',
      duration: 2,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSL06',
      courseName: 'Networks Laboratory',
      facultyId: 'FWL-04',
      facultyName: 'Dr. A. Balamurugan',
      day: 'THU',
      period: 'P2',
      room: 'Network Lab',
      sessionType: 'LAB',
      duration: 2,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC14',
      courseName: 'Compiler Design',
      facultyId: 'FWL-03',
      facultyName: 'Dr. S. Karpusamy',
      day: 'THU',
      period: 'P3',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC01',
      courseName: 'Advanced Data Structures',
      facultyId: 'FWL-01',
      facultyName: 'Dr. T. Rajasekaran',
      day: 'THU',
      period: 'P4',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC10',
      courseName: 'Operating Systems',
      facultyId: 'FWL-22',
      facultyName: 'Mr. R. Manikandan',
      day: 'THU',
      period: 'P5',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC12',
      courseName: 'Software Engineering',
      facultyId: 'FWL-05',
      facultyName: 'Mrs. P. Shanthi',
      day: 'THU',
      period: 'P6',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSL04',
      courseName: 'Aptitude & Soft Skills Training',
      facultyId: 'FWL-22',
      facultyName: 'Mr. R. Manikandan',
      day: 'THU',
      period: 'P7',
      room: 'LH-101',
      sessionType: 'OTHER',
      duration: 1,
    },

    // --- FRIDAY ---
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC14',
      courseName: 'Compiler Design',
      facultyId: 'FWL-03',
      facultyName: 'Dr. S. Karpusamy',
      day: 'FRI',
      period: 'P1',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC10',
      courseName: 'Operating Systems',
      facultyId: 'FWL-22',
      facultyName: 'Mr. R. Manikandan',
      day: 'FRI',
      period: 'P2',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC15',
      courseName: 'Computer Networks',
      facultyId: 'FWL-04',
      facultyName: 'Dr. A. Balamurugan',
      day: 'FRI',
      period: 'P3',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC12',
      courseName: 'Software Engineering',
      facultyId: 'FWL-05',
      facultyName: 'Mrs. P. Shanthi',
      day: 'FRI',
      period: 'P4',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSP01',
      courseName: 'Project Work Phase I',
      facultyId: 'FWL-03',
      facultyName: 'Dr. S. Karpusamy',
      day: 'FRI',
      period: 'P5',
      room: 'LH-101',
      sessionType: 'PBL',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC01',
      courseName: 'Advanced Data Structures',
      facultyId: 'FWL-01',
      facultyName: 'Dr. T. Rajasekaran',
      day: 'FRI',
      period: 'P6',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSS02',
      courseName: 'Sports & Extracurriculars',
      facultyId: 'FWL-03',
      facultyName: 'Dr. S. Karpusamy',
      day: 'FRI',
      period: 'P7',
      room: 'Sports Complex',
      sessionType: 'OTHER',
      duration: 1,
    },
  ];

  const inserted = await TimetableSession.insertMany(sessions);
  console.log(`[Seed] Successfully seeded ${inserted.length} timetable sessions across Mon-Fri.`);
  return { version, sessions: inserted };
}

module.exports = { seedTimetable };
